
const DebugList_ DebugList[] =
{
	{ // GHZ
		16,
		{
			//  map            id            subtype  frame   vram
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Crab,     ID_Crabmeat,         0,    0,    0x400  },
			{ Map_Buzz,     ID_BuzzBomber,       0,    0,    0x444  },
			{ Map_Chop,     ID_Chopper,          0,    0,    0x47B  },
			{ Map_Spike,    ID_Spikes,           0,    0,    0x51B  },
			{ Map_Plat_GHZ, ID_BasicPlatform,    0,    0,    0x4000 },
			{ Map_PRock,    ID_PurpleRock,       0,    0,    0x63D0 },
			{ Map_Moto,     ID_MotoBug,          0,    0,    0x4F0  },
			{ Map_Spring,   ID_Springs,          0,    0,    0x523  },
			{ Map_Newt,     ID_Newtron,          0,    0,    0x249B },
			{ Map_Edge,     ID_EdgeWalls,        0,    0,    0x434C },
			{ Map_GBall,    ID_Obj19,            0,    0,    0x43AA },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
			{ Map_GRing,    ID_GiantRing,        0,    0,    0x2400 },
			{ Map_Bonus,    ID_HiddenBonus,      1,    1,    0x84B6 },
		}
	},
	{ // LZ
		25,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Spring,   ID_Springs,          0,    0,    0x523  },
			{ Map_Jaws,     ID_Jaws,             8,    0,    0x2486 },
			{ Map_Burro,    ID_Burrobot,         0,    2,    0x84A6 },
			{ Map_Harp,     ID_Harpoon,          0,    0,    0x3CC  },
			{ Map_Harp,     ID_Harpoon,          2,    3,    0x3CC  },
			{ Map_Push,     ID_PushBlock,        0,    0,    0x43DE },
			{ Map_But,      ID_Button,           0,    0,    0x513  },
			{ Map_Spike,    ID_Spikes,           0,    0,    0x51B  },
			{ Map_MBlockLZ, ID_MovingBlock,      4,    0,    0x43BC },
			{ Map_LBlock,   ID_LabyrinthBlock,   1,    0,    0x43E6 },
			{ Map_LBlock,   ID_LabyrinthBlock,   0x13, 1,    0x43E6 },
			{ Map_LBlock,   ID_LabyrinthBlock,   5,    0,    0x43E6 },
			{ Map_Gar,      ID_Gargoyle,         0,    0,    0x443E },
			{ Map_LBlock,   ID_LabyrinthBlock,   0x27, 2,    0x43E6 },
			{ Map_LBlock,   ID_LabyrinthBlock,   0x30, 3,    0x43E6 },
			{ Map_LConv,    ID_LabyrinthConvey,  0x7F, 0,    0x3F6  },
			{ Map_Orb,      ID_Orbinaut,         0,    0,    0x467  },
			{ Map_Bub,      ID_Bubble,           0x84, 0x13, 0x8348 },
			{ Map_WFall,    ID_Waterfall,        2,    2,    0xC259 },
			{ Map_WFall,    ID_Waterfall,        9,    9,    0xC259 },
			{ Map_Pole,     ID_Pole,             0,    0,    0x43DE },
			{ Map_Flap,     ID_FlapDoor,         2,    0,    0x4328 },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
		}
	},
	{ // MZ
		18,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Buzz,     ID_BuzzBomber,       0,    0,    0x444  },
			{ Map_Spike,    ID_Spikes,           0,    0,    0x51B  },
			{ Map_Spring,   ID_Springs,          0,    0,    0x523  },
			{ Map_Fire,     ID_LavaMaker,        0,    0,    0x345  },
			{ Map_Brick,    ID_MarbleBrick,      0,    0,    0x4000 },
			{ Map_Geyser,   ID_GeyserMaker,      0,    0,    0x63A8 },
			{ Map_LWall,    ID_LavaWall,         0,    0,    0x63A8 },
			{ Map_Push,     ID_PushBlock,        0,    0,    0x42B8 },
			{ Map_Yad,      ID_Yadrin,           0,    0,    0x247B },
			{ Map_Smab,     ID_SmashBlock,       0,    0,    0x42B8 },
			{ Map_MBlock,   ID_MovingBlock,      0,    0,    0x2B8  },
			{ Map_CFlo,     ID_CollapseFloor,    0,    0,    0x62B8 },
			{ Map_LTag,     ID_LavaTag,          0,    0,    0x8680 },
			{ Map_Bas,      ID_Basaran,          0,    0,    0x4B8  },
			{ Map_Cat,      ID_Caterkiller,      0,    0,    0x24FF },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
		}
	},
	{ // SLZ
		15,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Elev,     ID_Elevator,         0,    0,    0x4000 },
			{ Map_CFlo,     ID_CollapseFloor,    0,    2,    0x44E0 },
			{ Map_Plat_SLZ, ID_BasicPlatform,    0,    0,    0x4000 },
			{ Map_Circ,     ID_CirclingPlatform, 0,    0,    0x4000 },
			{ Map_Stair,    ID_Staircase,        0,    0,    0x4000 },
			{ Map_Fan,      ID_Fan, 	         0,    0,    0x43A0 },
			{ Map_Seesaw,   ID_Seesaw,           0,    0,    0x374  },
			{ Map_Spring,   ID_Springs,          0,    0,    0x523  },
			{ Map_Fire,     ID_LavaMaker,        0,    0,    0x480  },
			{ Map_Scen,     ID_Scenery,          0,    0,    0x44D8 },
			{ Map_Bomb,     ID_Bomb,             0,    0,    0x400  },
			{ Map_Orb,      ID_Orbinaut,         0,    0,    0x2429 },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
		}
	},
	{ // SYZ
		15,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Spike,    ID_Spikes,           0,    0,    0x51B  },
			{ Map_Spring,   ID_Springs,          0,    0,    0x523  },
			{ Map_Roll,     ID_Roller,           0,    0,    0x4B8  },
			{ Map_Light,    ID_SpinningLight,    0,    0,    0      },
			{ Map_Bump,     ID_Bumper,           0,    0,    0x380  },
			{ Map_Crab,     ID_Crabmeat,         0,    0,    0x400  },
			{ Map_Buzz,     ID_BuzzBomber,       0,    0,    0x444  },
			{ Map_Yad,      ID_Yadrin,           0,    0,    0x247B },
			{ Map_Plat_SYZ, ID_BasicPlatform,    0,    0,    0x4000 },
			{ Map_FBlock,   ID_FloatingBlock,    0,    0,    0x4000 },
			{ Map_But,      ID_Button,           0,    0,    0x513  },
			{ Map_Cat,      ID_Caterkiller,      0,    0,    0x24FF },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
		}
	},
	{ // SBZ
		29,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Monitor,  ID_Monitor,          0,    0,    0x680  },
			{ Map_Bomb,     ID_Bomb,             0,    0,    0x400  },
			{ Map_Orb,      ID_Orbinaut,         0,    0,    0x429  },
			{ Map_Cat,      ID_Caterkiller,      0,    0,    0x22B0 },
			{ Map_BBall,    ID_SwingingPlatform, 7,    2,    0x4391 },
			{ Map_Disc,     ID_RunningDisc,      0xE0, 0,    0xC344 },
			{ Map_MBlock,   ID_MovingBlock,      0x28, 2,    0x22C0 },
			{ Map_But,      ID_Button,           0,    0,    0x513  },
			{ Map_Trap,     ID_SpinPlatform,     3,    0,    0x4492 },
			{ Map_Spin,     ID_SpinPlatform,     0x83, 0,    0x4DF  },
			{ Map_Saw,      ID_Saws,             2,    0,    0x43B5 },
			{ Map_CFlo,     ID_CollapseFloor,    0,    0,    0x43F5 },
			{ Map_MBlock,   ID_MovingBlock,      0x39, 3,    0x4460 },
			{ Map_Stomp,    ID_ScrapStomp,       0,    0,    0x22C0 },
			{ Map_ADoor,    ID_AutoDoor,         0,    0,    0x42E8 },
			{ Map_Stomp,    ID_ScrapStomp,       0x13, 1,    0x22C0 },
			{ Map_Saw,      ID_Saws,             1,    0,    0x43B5 },
			{ Map_Stomp,    ID_ScrapStomp,       0x24, 1,    0x22C0 },
			{ Map_Saw,      ID_Saws,             4,    2,    0x43B5 },
			{ Map_Stomp,    ID_ScrapStomp,       0x34, 1,    0x22C0 },
			{ Map_VanP,     ID_VanishPlatform,   0,    0,    0x44C3 },
			{ Map_Flame,    ID_Flamethrower,     0x64, 0,    0x83D9 },
			{ Map_Flame,    ID_Flamethrower,     0x64, 0xB,  0x83D9 },
			{ Map_Elec,     ID_Electro,          4,    0,    0x47E  },
			{ Map_Gird,     ID_Girder,           0,    0,    0x42F0 },
			{ Map_Invis,    ID_Invisibarrier,    0x11, 0,    0x8680 },
			{ Map_Hog,      ID_BallHog,          4,    0,    0x2302 },
			{ Map_Lamp,     ID_Lamppost,         1,    0,    0x7A0  },
		}
	},
	{ // Ending
#if JP1
		2,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Ring,     ID_Rings,            0,    8,    0x27B2 },
		}
#else
		13,
		{
			{ Map_Ring,     ID_Rings,            0,    0,    0x27B2 },
			{ Map_Bump,     ID_Bumper,           0,    0,    0x380  },
			{ Map_Animal2,  ID_Animals,          0xA,  0,    0x5A0  },
			{ Map_Animal2,  ID_Animals,          0xB,  0,    0x5A0  },
			{ Map_Animal2,  ID_Animals,          0xC,  0,    0x5A0  },
			{ Map_Animal1,  ID_Animals,          0xD,  0,    0x553  },
			{ Map_Animal1,  ID_Animals,          0xE,  0,    0x553  },
			{ Map_Animal1,  ID_Animals,          0xF,  0,    0x573  },
			{ Map_Animal1,  ID_Animals,          0x10, 0,    0x573  },
			{ Map_Animal2,  ID_Animals,          0x11, 0,    0x585  },
			{ Map_Animal3,  ID_Animals,          0x12, 0,    0x593  },
			{ Map_Animal2,  ID_Animals,          0x13, 0,    0x565  },
			{ Map_Animal3,  ID_Animals,          0x14, 0,    0x5B3  },
		}
#endif
	},
};